# -*- coding: utf-8 -*-
# Automatically generated by pyrcc5 — replace with a real compiled file
# when you add icons via resources.qrc + pyrcc5.
#
# For now this stub prevents ImportError on plugin load.

def qInitResources():
    pass

def qCleanupResources():
    pass
